# Generated by Django 4.1.1 on 2022-09-09 02:56

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="image",
            field=models.ImageField(
                upload_to=uploader.models.generate_media_path, verbose_name="画像"
            ),
        ),
    ]
