# Generated by Django 4.1.1 on 2022-09-09 04:34

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ("uploader", "0002_alter_uploadedimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=uploader.models.generate_media_path,
                        verbose_name="ファイル",
                    ),
                ),
            ],
        ),
    ]
