# Generated by Django 4.1.1 on 2022-10-06 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bureau",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="局URLコード")),
                (
                    "identifier",
                    models.SlugField(max_length=4, unique=True, verbose_name="局識別子"),
                ),
                ("name", models.CharField(max_length=8, verbose_name="局名")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="配置順"),
                ),
                (
                    "markdown_text",
                    models.TextField(blank=True, null=True, verbose_name="局紹介（マークダウン）"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="委員会URLコード")),
                (
                    "identifier",
                    models.SlugField(max_length=8, unique=True, verbose_name="委員会識別子"),
                ),
                ("name", models.CharField(max_length=32, verbose_name="委員会名")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="配置順"),
                ),
                (
                    "markdown_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="委員会紹介（マークダウン）"
                    ),
                ),
                (
                    "related_bureaus",
                    models.ManyToManyField(
                        blank=True,
                        related_name="division_bureaus",
                        to="blog.bureau",
                        verbose_name="関連局",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="タイトル")),
                ("markdown_text", models.TextField(verbose_name="本文（マークダウン）")),
                ("is_draft", models.BooleanField(default=False, verbose_name="下書き")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最終更新日時"),
                ),
                (
                    "bureau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="article_bureau",
                        to="blog.bureau",
                        verbose_name="局",
                    ),
                ),
                (
                    "committees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="article_divisions",
                        to="blog.committee",
                        verbose_name="委員会",
                    ),
                ),
            ],
        ),
    ]
