# Generated by Django 4.1.1 on 2022-09-09 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bureau",
            fields=[
                (
                    "code",
                    models.SlugField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="局コード",
                    ),
                ),
                ("name", models.CharField(max_length=8, verbose_name="局名")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="配置順"),
                ),
                ("markdown_text", models.TextField(verbose_name="局紹介（マークダウン）")),
            ],
        ),
        migrations.AlterField(
            model_name="article",
            name="markdown_text",
            field=models.TextField(verbose_name="本文（マークダウン）"),
        ),
        migrations.AddField(
            model_name="article",
            name="bureau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_bureau",
                to="blog.bureau",
            ),
        ),
    ]
