# Generated by Django 4.1.1 on 2022-09-09 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_bureau_alter_article_markdown_text_article_bureau"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_draft",
            field=models.BooleanField(default=False, verbose_name="下書き"),
        ),
        migrations.AlterField(
            model_name="article",
            name="bureau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_bureau",
                to="blog.bureau",
                verbose_name="局",
            ),
        ),
    ]
