# Generated by Django 4.1.1 on 2022-09-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_article_is_draft_alter_article_bureau"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="bureau",
        ),
        migrations.CreateModel(
            name="Committee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=4, verbose_name="委員会コード")),
                ("name", models.CharField(max_length=32, verbose_name="委員会名")),
                ("markdown_text", models.TextField(verbose_name="局紹介（マークダウン）")),
                (
                    "bureau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comittee_bureau",
                        to="blog.bureau",
                        verbose_name="局",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_committee",
                to="blog.committee",
                verbose_name="局",
            ),
        ),
    ]
