# Generated by Django 4.1.1 on 2022-09-09 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_article_bureau_committee_article_committee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_committee",
                to="blog.committee",
                verbose_name="委員会",
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="markdown_text",
            field=models.TextField(verbose_name="委員会紹介（マークダウン）"),
        ),
    ]
