# Generated by Django 4.1.1 on 2022-09-10 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_article_committee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="committee",
        ),
        migrations.RemoveField(
            model_name="committee",
            name="bureau",
        ),
        migrations.RemoveField(
            model_name="committee",
            name="id",
        ),
        migrations.AddField(
            model_name="article",
            name="bureau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_bureau",
                to="blog.bureau",
                verbose_name="局",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="committees",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="article_divisions",
                to="blog.committee",
                verbose_name="委員会",
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="related_bureaus",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="division_bureaus",
                to="blog.bureau",
                verbose_name="関連局",
            ),
        ),
        migrations.AlterField(
            model_name="bureau",
            name="markdown_text",
            field=models.TextField(blank=True, null=True, verbose_name="局紹介（マークダウン）"),
        ),
        migrations.AlterField(
            model_name="committee",
            name="code",
            field=models.SlugField(
                max_length=8,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="委員会コード",
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="markdown_text",
            field=models.TextField(blank=True, null=True, verbose_name="委員会紹介（マークダウン）"),
        ),
    ]
