# Generated by Django 4.1.1 on 2022-09-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_article_committee_remove_committee_bureau_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="committees",
            field=models.ManyToManyField(
                blank=True,
                related_name="article_divisions",
                to="blog.committee",
                verbose_name="委員会",
            ),
        ),
        migrations.AlterField(
            model_name="committee",
            name="related_bureaus",
            field=models.ManyToManyField(
                blank=True,
                related_name="division_bureaus",
                to="blog.bureau",
                verbose_name="関連局",
            ),
        ),
    ]
