# Generated by Django 4.1.1 on 2022-09-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_committee_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="code",
            field=models.SlugField(
                max_length=16,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="委員会コード",
            ),
        ),
    ]
