# Generated by Django 4.1.1 on 2022-09-11 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_committee_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="bureau",
            name="id",
            field=models.AutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="committee",
            name="id",
            field=models.AutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="bureau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_bureau",
                to="blog.bureau",
                to_field="code",
                verbose_name="局",
            ),
        ),
        migrations.AlterField(
            model_name="bureau",
            name="code",
            field=models.SlugField(max_length=4, unique=True, verbose_name="局コード"),
        ),
        migrations.AlterField(
            model_name="committee",
            name="code",
            field=models.SlugField(max_length=16, unique=True, verbose_name="委員会コード"),
        ),
    ]
