# Generated by Django 4.1.1 on 2022-09-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_bureau_id_committee_id_alter_article_bureau_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="bureau",
        ),
        migrations.RemoveField(
            model_name="article",
            name="committees",
        ),
        migrations.RemoveField(
            model_name="committee",
            name="related_bureaus",
        ),
    ]
