# Generated by Django 4.1.1 on 2022-09-11 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_remove_article_bureau_remove_article_committees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="bureau",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="article_bureau",
                to="blog.bureau",
                to_field="code",
                verbose_name="局",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="committees",
            field=models.ManyToManyField(
                blank=True,
                related_name="article_divisions",
                to="blog.committee",
                verbose_name="委員会",
            ),
        ),
        migrations.AddField(
            model_name="committee",
            name="related_bureaus",
            field=models.ManyToManyField(
                blank=True,
                related_name="division_bureaus",
                to="blog.bureau",
                verbose_name="関連局",
            ),
        ),
    ]
