# Generated by Django 4.1.1 on 2022-09-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_committee_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committee",
            name="identifier",
            field=models.SlugField(unique=True, verbose_name="委員会識別子"),
        ),
    ]
