# Generated by Django 4.1.1 on 2022-10-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_alter_committee_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bureau",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="committee",
            name="name_en",
        ),
        migrations.AddField(
            model_name="bureau",
            name="identifier",
            field=models.SlugField(
                blank=True, max_length=4, null=True, unique=True, verbose_name="局識別子"
            ),
        ),
        migrations.AlterField(
            model_name="bureau",
            name="code",
            field=models.SlugField(unique=True, verbose_name="局URLコード"),
        ),
        migrations.AlterField(
            model_name="committee",
            name="code",
            field=models.SlugField(unique=True, verbose_name="委員会URLコード"),
        ),
        migrations.AlterField(
            model_name="committee",
            name="identifier",
            field=models.SlugField(
                blank=True, max_length=8, null=True, unique=True, verbose_name="委員会識別子"
            ),
        ),
    ]
