# Generated by Django 4.1.1 on 2022-10-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_remove_bureau_name_en_remove_committee_name_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bureau",
            name="identifier",
            field=models.SlugField(max_length=4, unique=True, verbose_name="局識別子"),
        ),
        migrations.AlterField(
            model_name="committee",
            name="identifier",
            field=models.SlugField(max_length=8, unique=True, verbose_name="委員会識別子"),
        ),
    ]
