# Generated by Django 4.0 on 2022-08-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=256, unique=True, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=16, unique=True, verbose_name="ユーザー名"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ユーザー")),
                ("is_staff", models.BooleanField(default=False, verbose_name="スタッフ")),
                ("is_admin", models.BooleanField(default=False, verbose_name="管理者")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
